# Generated by Django 5.0.3 on 2024-03-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createapi', '0002_alter_weatherdata_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={},
        ),
    ]
