# Generated by Django 5.0.3 on 2024-03-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createapi', '0004_alter_weatherdata_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='icon',
            field=models.CharField(max_length=10),
        ),
    ]
